### ISSUE TITLE
Support Request - video/mp4

### ISSUE THREAD

**Issue by MOVZX** [ScreamingHawk/phone-saver#12]
Support request. Generated by Phone Saver.

Intent type: video/mp4
Intent action: android.intent.action.SEND

More information: I want to save some GIFs from Telegram.

Thank you

**Comment by ScreamingHawk** [comment]
I don't have telegram so I haven't been able to test with this app specifically. 

Pushing a new version to Google Play now. 

Thanks for using the app!

**Comment by ScreamingHawk** [comment]
The new version should be live now. Let me know if it work or you are still seeing issues, so I can close this ticket.

**Comment by Chen-pan** [comment]
+1

**Comment by ScreamingHawk** [comment]
@Chen-pan This feature should be live in v1.8. Can you check the Credits page to see what version you are on? F-Droid is a bit slow on releases so that might be the case for you.

**Comment by Chen-pan** [comment]
@ScreamingHawk That's exactly the issue. I am on v1.6 from F-Droid. I'll wait for the update and get back with the result. Thanks a lot mate.

**Comment by Chen-pan** [comment]
@ScreamingHawk Should this work with trust app?

**Comment by ScreamingHawk** [comment]
@Chen-pan What is trust app?

**Comment by Chen-pan** [comment]
@ScreamingHawk Sorry that was supposed to be Twitter for android. Typo.

**Comment by ScreamingHawk** [comment]
@Chen-pan Looks like a bug. Tracking it here: #21
