### ISSUE TITLE
Support Request - video/*

### ISSUE THREAD

**Issue by basilgohar** [ScreamingHawk/phone-saver#16]
Support request. Generated by Phone Saver.

Intent type: video/*
Intent action: android.intent.action.SEND
Text: https://test.masjidomarohio.org/wp-content/uploads/2017/05/Masjid-Omar-Open-House.mov
Subject: 

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Can you please check which version of Phone Saver you are using (in the Credits)? I added support for video files 2 days ago so this should be working.

**Comment by basilgohar** [comment]
I am using 1.6, the only and latest version available in F-Droid.  It just became available yesterday.

![screenshot_20170630-004607](https://user-images.githubusercontent.com/43361/27721394-022aef42-5d2e-11e7-902f-848212e3c828.png)

**Comment by basilgohar** [comment]
![screenshot_20170630-005035](https://user-images.githubusercontent.com/43361/27721420-2b8b1d3a-5d2e-11e7-9e3e-30c5f49692c6.png)

**Comment by ScreamingHawk** [comment]
Thanks @basilgohar. 

Video support was added in v1.7. F-Droid releases are automated but I have no idea what the schedule is for it. 

If you know how to push a release to F-Droid, let me know and I'll get it done for you now. Otherwise you'll just have to wait a bit for the repos to update.

**Comment by ScreamingHawk** [comment]
Or you can build from source yourself if you are desperate :)

**Comment by basilgohar** [comment]
Thank you for the follow-up.  Alas, I don't know how to push an F-Droid
release out.  But if that is the case, then you can close this issue. 
Thanks again!

**Comment by ScreamingHawk** [comment]
No problem! I'm tracking `video/*` support in ticket #12 if you have any issues after the update
