### ISSUE TITLE
Crashes when attempting to share HTML page from browser

### ISSUE THREAD

**Issue by protist** [ScreamingHawk/phone-saver#19]
Sorry, I don't have much information, but I'm not sure where to find logs or debugging information.

I installed Phone Saver, set up one default directory, then attempted to share something via Phone Saver. The app opened, but there were no directories to select, and nothing to do. After a second or so, I got the message `Phone Saver has stopped`. More than happy to provide more information; just let me know where to look.

LG G2 (D802)
Android 7.1.2
LineageOS 14.1-20170529-NIGHTLY-d802
Installed Phone Saver from F-Droid

**Comment by protist** [comment]
I was using Phone Saver 1.6, but I just saw 1.7 was pushed to F-Droid. I updated, but unfortunately this suffers from the same problem.

**Comment by ScreamingHawk** [comment]
I'm looking into this problem now. 

In the meantime, try adding a second directory. 
It'll be an extra click when you save but should stop the crashes too.

**Comment by ScreamingHawk** [comment]
@protist I haven't been able to replicate this issue. It could be the particular thing you are trying to share that is causing the issue. 

Can you give more information about what you are trying to share?

**Comment by protist** [comment]
Ah sorry, yes, I should have given more information before. I think your interpretation is correct; the source of the share is important.

Originally, I attempted to share a url from Firefox. That is, navigate to a page, then "share". This crashed Phone Saver. I tested sharing from Firefox to a file explorer instead, and it saved a plain text file correctly, so I guess that would be the mime type?

I tested sharing to Phone Saver again, but this time sharing an image from the gallery instead. This worked perfectly.

Finally, I also tested adding a second directory. This time, when I share from Firefox, Phone Saver does not immediately crash, but instead I am taken to the directory selection screen. However, as soon as I select one of the directories, it crashes again.

**Comment by ScreamingHawk** [comment]
Seems to be a problem saving direct HTML pages shared via a browser. I can replicate this issue now so will look into a fix. 

Thanks for the heads up.

**Comment by protist** [comment]
> Thanks for the heads up.

No worries! Thank *you* for the quick and pertinent response!

**Comment by ScreamingHawk** [comment]
Saving a web page directly no longer crashes the app. But I'm conflicted about how an HTML page should be saved. 

I'm going to close this ticket, but if you use the app to generate a ticket for HTML support and give me some idea about what you would expect to be saved, I'll definitely look to add it in.

**Comment by protist** [comment]
Thank you! I tested the new Phone Saver 2.2, and I can confirm that it doesn't crash. However, saving a "page" from Firefox is still not working. I don't think it's actually sharing HTML at all. In any case, I opened a new ticket, and I've put more information in that. Cheers.
