### ISSUE TITLE
Support Request - application/octet-stream

### ISSUE THREAD

**Issue by jakllsch** [ScreamingHawk/phone-saver#22]
Support request. Generated by Phone Saver.

Intent type: application/octet-stream
Intent action: android.intent.action.SEND

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Note to self: Check for and use `Content-Decomposition` if available. 

https://stackoverflow.com/a/20509354/2027146

**Comment by ScreamingHawk** [comment]
Live in v2.4

Let me know if you have any issues.

**Comment by ScreamingHawk** [comment]
v2.4 is now live in Google Play production stream

**Comment by jakllsch** [comment]
Works in v2.4 from F-Droid.
