### ISSUE TITLE
Saving to Removable SD card fails

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/phone-saver#26]
Saving to a removable SD card fails. 

There are so many different ways listed on the internet for how to do this and most of them seem like dirty hacks. The best approach to fix this will be to find an open source application that already handles saving to removable SD cards, and copy the implementation.

**Comment by ScreamingHawk** [comment]
Unfortunately, I don't have a device with a removable SD card, so testing this is going to be a problem.

**Comment by ScreamingHawk** [comment]
Completed #28 which may prevent adding SD card locations while I figure out how to correctly support them.

**Comment by ScreamingHawk** [comment]
https://github.com/inorichi/tachiyomi is an example of a project that can correctly save to an SD card

**Comment by ScreamingHawk** [comment]
Looking into a rewrite of the saving strategy. Seems like the other projects save to app storage and then move the file to external storage afterwards. 

This strategy has the bonus of keeping behaviour consistent across save strategies, which is not currently the save.

**Comment by amtlib-dot-dll** [comment]
See https://github.com/ScreamingHawk/phone-saver/issues/43. In newer Android only system applications cannot directly access external removable SD card without the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html).

**Comment by ScreamingHawk** [comment]
Closing this ticket in favour of #43
