### ISSUE TITLE
Special URL handling - REQUESTS GO HERE

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/phone-saver#35]
The more I play with this app, the more I want this feature. 

When sharing some sites with the intention to save the site, you actually want to save a particular thing in the site. e.g. When sharing imgur.com links I actually want to save each image in the album. 

This issue is a placeholder for requests for special handling.

**Comment by ScreamingHawk** [comment]
Twitter handling would be nice. Need to flesh out handling appropriately. User ideas appreciated. 

Related Twitter ticket #21

**Comment by amtlib-dot-dll** [comment]
You may rewrite this app to allow plugins, or it would be a huge work to support all sites. Look https://github.com/soimort/you-get#supported-sites and you might know how many work you would do. By the way, the UNIX philosophy is to "Do one thing and do it well" so personally speaking the URL saving feature https://github.com/ScreamingHawk/phone-saver/blob/eccbe247c1a36615ea1532d964d353eea0743c5f/app/src/main/java/link/standen/michael/phonesaver/activity/SaverActivity.kt#L327 is also unnecessary. You can just use you browser, or a terminal emulator with `curl` to achieve it.

**Comment by ScreamingHawk** [comment]
Yeah, this project has become a little bit of a mess. Could definitely do with some kind of plugin architecture. I intended to add it with ticket if there was any desire from users (you are the first). 

I'm completely self taught in Kotlin and Android so really appreciate your input. Thanks for the code review.

**Comment by amtlib-dot-dll** [comment]
Haha, actually I don't want a plugin feature, but only a phone saver app with no download feature. There might already be many plugin frameworks for Android apps, if there would be someone else calling for it.

**Comment by amtlib-dot-dll** [comment]
Or, embed Python into this app, and call the aforementioned scrapper.

**Comment by ScreamingHawk** [comment]
> only a phone saver app with no download feature

This was my original sentiment. Quickly discovered it would be much easier for my use cases if it was internet enabled. 

I've heard good things about [mobiwol](http://www.mobiwol.com/) if you want to block internet access to this app.

**Comment by amtlib-dot-dll** [comment]
Actually I know [how](https://github.com/LineageOS/android_frameworks_base/blob/74675369464fb49dd3cd0b6af62e4812ff8d9d97/core/java/android/net/NetworkPolicyManager.java#L52) to limit the network access of apps but it's unnecessary, because it's open sourced, isn't it? Well it's YOUR app, let it be what YOU want first.

**Comment by ScreamingHawk** [comment]
Closing this. I'd rather a separate ticket per site
