### ISSUE TITLE
Support to save emails

### ISSUE THREAD

**Issue by AntonioND** [ScreamingHawk/phone-saver#37]
There are some apps, like WhatsApp, that let you send something to an email app, but not through a share menu. It would be great if this app could intercept them and save them to the SD card as well.

**Comment by ScreamingHawk** [comment]
Hey @AntonioND 

As far as I know, there's no way to *intercept* emails. 

What I could (probably) do is allow Phone Saver to save emails that are shared to it and then forward the email request via the share feature again (where you would pick the email client). Would this work for you?

**Comment by AntonioND** [comment]
I don't think I've explained myself correctly. The problem is that WhatsApp sends a lot of files to the email client to attach and they don't fit in an email. If somehow this program disguised itself as an email client and saved the files to the storage instead, that would be perfect.

**Comment by ScreamingHawk** [comment]
That sounds more reasonable. I'll have a look into it.
