### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by OffifialMITX** [ScreamingHawk/phone-saver#39]
Ever since I've got this app it gets tons of upgrades hut no noteable changes.

**Comment by ScreamingHawk** [comment]
Fair enough. 

In the meantime, change log is effective the git commit history logs.

**Comment by OffifialMITX** [comment]
I did not understand the last 50% of all the sentences. Would you mind explaining it a little?

Am 17. Juli 2017 21:19:25 MESZ, schrieb Michael Standen <notifications@github.com>:
>Fair enough. 
>
>In the meantime, change log is effective the git commit history logs. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ScreamingHawk/phone-saver/issues/39#issuecomment-315854611

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by ScreamingHawk** [comment]
I will add a change log to the app. 

This is a list of the changes https://github.com/ScreamingHawk/phone-saver/commits/master
