### ISSUE TITLE
Support Request - text/plain

### ISSUE THREAD

**Issue by hackerb9** [ScreamingHawk/phone-saver#40]
Support request. Generated by Phone Saver.

Intent type: text/plain
Intent action: android.intent.action.SEND
Application Version: 2.5

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Hey, 

The currently released application version is v3.0. Can you please update the app? 

This may also be a duplicate of #30. Hard to tell with the lack of additional information.

**Comment by hackerb9** [comment]
Yes, it was a duplicate #30. Thank you.
