### ISSUE TITLE
Support Request - text/plain

### ISSUE THREAD

**Issue by Sarkasper** [ScreamingHawk/phone-saver#41]
Support request. Generated by Phone Saver.

Intent type: text/plain
Intent action: android.intent.action.SEND
Text: http://www.csszengarden.com/218/218.css
Subject: http://www.csszengarden.com/218/218.css
URL Content-Type: text/css
Application Version: 3.0

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Sorry I completely missed this! This is an easy add. Will add it shortly.

**Comment by ScreamingHawk** [comment]
Done. This will be available in the v3.2 release. Sorry for the delay
