### ISSUE TITLE
Support Request - */*

### ISSUE THREAD

**Issue by amtlib-dot-dll** [ScreamingHawk/phone-saver#42]
This request is hand-written by me. Already existed in https://github.com/ScreamingHawk/phone-saver/issues/3.

There are so many MIME types there and it is seldom possible for us to enumerate and handle all of them. However, for all kinds of sharing intents, we may only extract data from `EXTRA_STREAM` (or `EXTRA_TEXT` as a fallback) and apply the filename. It would be absolutely better when the user cannot save his or her MS Word documents, PDF documents, C++ source files, PSpice models, MATLAB figures, Photoshop settings files, ZIP archives, and files just with a MIME type of `*/*`. Currently this application fails to save it, and the user may just uninstall it and try another one instead.

Thank you very much!

**Comment by ScreamingHawk** [comment]
You have a good point here. My concern is that there's a *better* way to handle particular MIME types which will be missed. 

The current implementation forces the user to acknowledge a desire for a particular MIME type which then allows me to figure out the most appropriate way to handle the request. 

**Possible Solution**

What if there was a setting you could enable that *forces* saving requests, even if not explicitly supported. Would that solve this issue for you? 

I appreciate your feedback.

**Comment by amtlib-dot-dll** [comment]
Yeah, that would be great. Thank you very much!

**Comment by ScreamingHawk** [comment]
Done. 

This will be in the v3.2 release, now available in the Beta stream in the Play store. 

If you are using F-Droid you'll have to wait for the repo to update. I don't think I can force this.
