### ISSUE TITLE
Support Request - CJK characters

### ISSUE THREAD

**Issue by amtlib-dot-dll** [ScreamingHawk/phone-saver#44]
Related code: https://github.com/ScreamingHawk/phone-saver/blob/eccbe247c1a36615ea1532d964d353eea0743c5f/app/src/main/java/link/standen/michael/phonesaver/activity/SaverActivity.kt#L458

CJK characters and emojis are undesirably filtered. Furthermore, there is no need to filter filenames as all characters except `\x00` and `/` is allowed in UNIX filenames.

Thank you very much!

**Comment by amtlib-dot-dll** [comment]
As in https://github.com/ScreamingHawk/phone-saver/issues/31, this is essential for Korean users, not only a Korean translation.

**Comment by ScreamingHawk** [comment]
Fair enough. I can't recall the reason I originally added this. I suspect I noticed an issue when using a saved file in another app which didn't support the characters for whatever reason. Possibly also for file extension detection (stripping `.`). 

Would replacing the regex with `[^\x00/.]` fit your use case? Or do you have a better alternative? 

Really appreciate your code review.

**Comment by amtlib-dot-dll** [comment]
Probably there is no need to strip characters but use libraries to handle path names and filenames instead. Anyway, you may just add another switch for a different behaviour.

**Comment by ScreamingHawk** [comment]
Done. Tested with a Japanese domain. Correctly saves with テスト in the filename. Will push the release today. Let me know on this ticket if it needs to be reopened.
