### ISSUE TITLE
Notify MediaScanner when saving images, audios and videos

### ISSUE THREAD

**Issue by amtlib-dot-dll** [ScreamingHawk/phone-saver#45]
It is a common good practice to use https://developer.android.com/reference/android/media/MediaScannerConnection.html#scanFile(android.content.Context,%20java.lang.String%5B%5D,%20java.lang.String%5B%5D,%20android.media.MediaScannerConnection.OnScanCompletedListener) when saving media files to the storage, or the Gallery app and the Music app may not find it.

Thank you very much!

**Comment by ScreamingHawk** [comment]
I personally don't want this behaviour. But understand that other people might. 

I'll add this as a configurable setting.

**Comment by amtlib-dot-dll** [comment]
Thank you very much!

**Comment by ScreamingHawk** [comment]
Done. Will be available in v3.3, now in beta on Google Play. F-Droid updating takes however long F-Droid takes. 

Let me know if you have any problems with this implementation.
