### ISSUE TITLE
Request to support more text/ mime types

### ISSUE THREAD

**Issue by brarcher** [ScreamingHawk/phone-saver#50]
Intent type: text/csv
Intent action: android.intent.action.SEND
Application Version: 3.5

Details:
I've an application ([here](https://github.com/brarcher/budget-watch)) which can export data in either a CSV, JSON, or zip format. Previously I was able to export the data and have PhoneSaver save it. However, this was because I was improperly setting the type as "text/plain". When I went to fix this and share files with either "text/csv", "text/json", or "application/zip" mime types I found that PhoneSaver is unable to save the files. The content of the data is the same, only the type is different. The logs indicate that the mime type was simply not recognized:

```
11-21 20:07:27.124  4065  4065 I SaverActivity: Action: android.intent.action.SEND
11-21 20:07:27.124  4065  4065 I SaverActivity: Type: text/csv
11-21 20:07:27.124  4065  4065 I SaverActivity: No supporting method
```

I suspect (though perhaps you can verify) that changing the text/plain check in [SaverActivity.kt](https://github.com/ScreamingHawk/phone-saver/blob/3d9af0b23d4d79eb92aa0e374c0a8059634fcd01/app/src/main/java/link/standen/michael/phonesaver/activity/SaverActivity.kt#L129) may allow the application to save all text types:

- } else if (it.startsWith("text/plain")) {
+ } else if (it.startsWith("text/")) {

In addition, I see that the code paths which save image, audio, video, text, and octet-stream data is the same. May it be even simpler if the first attempt is to check if the data is a stream and save it regardless of the mime type, and the fallback would be to handle the EXTRA_TEXT case specifically if the mime type starts with "text/"? 

Regardless, thanks for creating this application!

**Comment by ScreamingHawk** [comment]
There's a lot that could be improved in this project... I'll have a look at testing for a stream. That sounds like an obvious improvement. Failing that I'll change the `text/` test as you've also suggested. I'll check for `application/zip` too. 

In the meantime you can set the `Force saving` flag in the settings to override the "not supported" behaviour.

**Comment by brarcher** [comment]
> I'll have a look at testing for a stream.

If it is helpful, I can help beta test the stream changes if you post an apk to try out.

**Comment by ScreamingHawk** [comment]
I usually release to the beta stream on the play store for beta testing. It's open for anyone to sign up to. 

Since you're using F-Droid I'll post a link to the apk here too

**Comment by ScreamingHawk** [comment]
http://evaporating.link/download.html?f=app-release.apk

Link will expire in a day or so

**Comment by brarcher** [comment]
> Unfortunately I don't have the time or resources to test this app to a level that makes me feel comfortable so I end up releasing a lot of bugs...

Having a few other apps that I made mostly for myself but also released on F-Droid and Google Play, I can appreciate your position. 

> Thanks so much for doing the hard work of not just logging a bug but finding and debugging the problem for me. It really is appreciated.

Honestly, I was trying to use PhoneSaver to test some changes in my app. When it did not work, I looked further to see if the issue was in my app or in PhoneSaver. Luckily, tracking it down was not too much trouble. (:

I took a look at the app posted in the link on an Android 7.1.1 VM. When my app shares a text stream with the text/plain mimetype, I find that PhoneSaver will create the file with the correct name but is contents are empty:
```
$ logcat
...
11-23 15:10:43.586  5743  5743 I SaverActivity: Action: android.intent.action.SEND
11-23 15:10:43.586  5743  5743 I SaverActivity: Type: text/plain
11-23 15:10:43.587  5743  5743 D SaverActivity: Text has stream
11-23 15:10:43.606  5743  5743 D SaverActivity: Converting mime: text/plain
11-23 15:10:43.607  5743  5743 D SaverActivity: Converted mime: text/plain
11-23 15:10:43.607  5743  5743 D SaverActivity: Converting filename: BudgetWatch.json
11-23 15:10:43.607  5743  5743 D SaverActivity: Adding extension txt to BudgetWatch.json
11-23 15:10:43.608  5743  5743 D SaverActivity: Converted filename: BudgetWatch.json.txt
11-23 15:10:43.637  5743  5743 I SaverActivity: Supported: true
11-23 15:10:43.637  5743  5743 I SaverActivity: Action: android.intent.action.SEND
11-23 15:10:43.637  5743  5743 I SaverActivity: Type: text/plain
11-23 15:10:43.638  5743  5743 D SaverActivity: Text has stream
11-23 15:10:43.639  5743  5743 D SaverActivity: Converting mime: text/plain
11-23 15:10:43.640  5743  5743 D SaverActivity: Converted mime: text/plain
11-23 15:10:43.640  5743  5743 D SaverActivity: Converting filename: BudgetWatch.json
11-23 15:10:43.640  5743  5743 D SaverActivity: Adding extension txt to BudgetWatch.json
11-23 15:10:43.640  5743  5743 D SaverActivity: Converted filename: BudgetWatch.json.txt
11-23 15:10:43.641  5743  5743 D SaverActivity: Adding postfix to BudgetWatch.json.txt
11-23 15:10:43.642  5743  5743 D SaverActivity: Saving /exportPath/BudgetWatch.json to /storage/emulated/0/BudgetWatch.json.1.txt
...
$ stat BudgetWatch.json.txt                                                                                                  
  File: `BudgetWatch.json.txt'
  Size: 0	 Blocks: 0	 IO Blocks: 4096	regular empty file
...
```

This is a regression from the previous version, as previously data was saved (though it may have extra data at the end).

When my app reports other mimetypes (text/csv, text/json, application/zip) PhoneSaver will attempt to save them but the resulting files are also empty.

**Comment by ScreamingHawk** [comment]
Put `==` instead of `!=` 😭 

Should be good now. Releasing another version to play store beta stream and link here: http://evaporating.link/download.html?f=app-release.apk

**Comment by brarcher** [comment]
That did the trick. PhoneSaver was able save text/csv, text/json, and application/zip, and the contents of the saved files were an exact match to the originals (compared md5 sums). :shipit:!
