### ISSUE TITLE
Saved data is sometimes incomplete or zero padded

### ISSUE THREAD

**Issue by brarcher** [ScreamingHawk/phone-saver#51]
This is found in v3.5 on F-Droid. The files which are saved using PhoneSaver are often not the exact files which are sent to it. There are two examples. 

1) If the file being sent is small it ends up zero padded. For example, the following file is sent using [this](https://github.com/brarcher/loyalty-card-locker) application's backup feature:
```
$ cat LoyaltyCardKeychain.csv                                                                                                    
"_id",store,note,cardid,barcodetype
7,name 1,,aefa,AZTEC
2,name 2,,4676543,CODE_128
3,name 3,,awef,CODE_128
4,name 4,,wefa,AZTEC
```
When the file is sent and saved by PhoneSaver the result is a much larger file:
```
$ stat LoyaltyCardKeychain.csv  LoyaltyCardKeychain.1.csv                                                                    
  File: `LoyaltyCardKeychain.csv'
  Size: 134	 Blocks: 8	 IO Blocks: 4096	regular file
Device: 13h/19d	 Inode: 40	 Links: 1
Access: (660/-rw-rw----)	Uid: (0/    root)	Gid: (1015/sdcard_rw)
Access: 2017-11-21 16:48:00.615000000
Modify: 2017-11-21 19:07:57.035000000
Change: 2017-11-21 19:07:57.035000000
  File: `LoyaltyCardKeychain.1.csv'
  Size: 1024	 Blocks: 8	 IO Blocks: 4096	regular file
Device: 13h/19d	 Inode: 44	 Links: 1
Access: (660/-rw-rw----)	Uid: (0/    root)	Gid: (1015/sdcard_rw)
Access: 2017-11-21 18:15:10.305000000
Modify: 2017-11-21 18:15:10.315000000
Change: 2017-11-21 18:15:10.315000000
```
The reason the file is larger is it is zero padded to 1024 bytes:
```
$ xxd LoyaltyCardKeychain.1.csv | tail -n 3
000003d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000003f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

2) If the file being sent is over 1024 bytes but is not on a 1K boundary extra data appears at the end of the file. An example of this is [this](https://github.com/brarcher/budget-watch) application exporting data:
```
$ cat BudgetWatch.json | tail -n 10                                                                                              
      "_id": "Utilities",
      "type": "BUDGET",
      "value": 180.0
   },
   {
      "_id": "a",
      "type": "BUDGET",
      "value": 1.0
   }
]
```
However when the data is saved with PhoneSaver the ending of the file is different:
```
$ cat BudgetWatch.json.txt  | tail -n 10                                                                                         
      "type": "BUDGET",
      "value": 1.0
   }
]   "_id": "HSA Paid",
      "type": "BUDGET",
      "value": 0.0
   },
   {
      "_id": "HSA to Payback",
```
That last bit in the file after the ] is actually data which appears earlier in the file, copied again.

I believe the reason both of these are happening is due to how data from streams is being copied and saved, namely the following from [SaverActivity.kt](https://github.com/ScreamingHawk/phone-saver/blob/3d9af0b23d4d79eb92aa0e374c0a8059634fcd01/app/src/main/java/link/standen/michael/phonesaver/activity/SaverActivity.kt):
```
bos = BufferedOutputStream(FileOutputStream(fout, false))
val buf = ByteArray(1024)
bis.read(buf)
do {
   bos.write(buf)
} while (bis.read(buf) != -1)
```
This ignores the number of bytes which are read from bis, and assumes that exactly 1024 bytes are read each time until the file is complete. This is only true if the file's size is a multiple of 1K. For files which are smaller than that the excess in the ByteArray is being written out. For files larger than that but not on a 1K boundary the previous read's data is making it into the file on the write from the last read.

Not too familiar with the language, the following is close to what needs to happen instead:
```
bos = BufferedOutputStream(FileOutputStream(fout, false))
val buf = ByteArray(1024)
val bytesRead = bis.read(buf)
while(bytesRead != -1)
{
   bos.write(buf, /*offset*/ 0, /*length*/ bytesRead)
   bytesRead = bis.read(buf)
}
```

**Comment by ScreamingHawk** [comment]
@brarcher Great catch! I'll fix this up today. You're pretty close with the language implementation.

**Comment by brarcher** [comment]
This issue is resolved. Thanks!
