### ISSUE TITLE
Can't save pictures from Google Assistant

### ISSUE THREAD

**Issue by AeliusSaionji** [ScreamingHawk/phone-saver#52]
I'm on Oreo 8.1 and this doesn't work more often than not.

I'll start submitting more specific bug reports, but to start:

Google Assistant > Share Screenshot > Phone Saver

Success message appears, but no picture is saved.

**Comment by AeliusSaionji** [comment]
You know what, I spoke too soon. For some reason it's taking several minutes for my gallery to realize the picture is there.

**Comment by ScreamingHawk** [comment]
:) No problem. 

There is a setting `Register with media scanner` that you can enable which make the image appear immediately.

**Comment by AeliusSaionji** [comment]
Thanks, yeah I'm using Simple Gallery and I assumed the media scanner was just for Google photos. All is well with this!
