### ISSUE TITLE
Phone Saver is affected by a bug on certain Custom ROMs

### ISSUE THREAD

**Issue by STPKITT** [ScreamingHawk/phone-saver#53]
Hello,
using a Samsung Galaxy Grand DUOS GT-I9082 running LineageOS 13.0 6.0.1_r79 from July 2017 I discovered that Phone Saver is affected by the bug treated in the following links. In those links you can see that the whole problem is fixed on recent Custom ROMs. Trouble is that a lot of devices are stuck on older ROM releases so Phone Saver development should do the necessary steps to avoid it like the developers on the app "Conversations" did (look at the last link).

https://issuetracker.google.com/issues/64434571

https://jira.lineageos.org/browse/BUGBASH-1052

https://gitlab.com/fdroid/fdroiddata/issues/979

https://github.com/siacs/Conversations/issues/2785

Thanks and greetings!

**Comment by ScreamingHawk** [comment]
Thanks! 

I've updated the build tools to `27.0.3` as per the reference. Will push a release through to Play Store shortly.

**Comment by ScreamingHawk** [comment]
Pushed and rolled out. You should see an update from Play Store any moment. 
If you use F-Droid then F-Droid will update when F-Droid feels like it.

**Comment by STPKITT** [comment]
Awesome! Thank you!
