### ISSUE TITLE
ICS (calendar event) doesn't find it's place.

### ISSUE THREAD

**Issue by NitroNils** [ScreamingHawk/phone-saver#65]
Got an email w/ a ICS which I can't 'land' in my calendar. Tried saving and downloading, but won't open w/ calendar.
Can probaly locate it in the filesystem somewhere, but would be nice to capture the event w/ cal.

**Comment by ScreamingHawk** [comment]
Hi @NitroNils 

When sharing to Phone Saver do you get the "Not Supported" message? 
If so, could you use the link to create a GitHub issue. That will give me more information to work with. 

You could also try enabling the `Force Saving` feature to by pass this support test. 

Hope that helps. 

Cheers,
Michael

**Comment by NitroNils** [comment]
OK, next time it pops up I will look into it (when I order train tickets online. Maybe not you're apps field actually.).

**Comment by ScreamingHawk** [comment]
This ticket is now many months old. I'm closing it. Can be reopened if a generated bug request is posted
