### ISSUE TITLE
Support Request - text/plain

### ISSUE THREAD

**Issue by KristobalJunta** [ScreamingHawk/phone-saver#66]
Support request. Generated by Phone Saver.

Intent type: text/plain
Intent action: android.intent.action.SEND
Text: https://telegram.org/js/telegram-widget.js
Subject: https://telegram.org/js/telegram-widget.js
URL Content-Type: application/javascript
Application Version: 3.7

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Hi @KristobalJunta You are using a very old version of Phone Saver. Could you please update to v4.0.1 or higher. This should enable saving of `js` files. 

Alternatively, you can toggle the `Force Saving` flag in the settings, which should allow you to save this.

**Comment by ScreamingHawk** [comment]
I'm going to close this ticket, let me know if the problem persists in a more recent version and I can re-open

**Comment by KristobalJunta** [comment]
Yes. Sorry for bothering. I forgot that PhoneSaver was installed via Fdroid and not PlayStore, and haven't updated that in a while 😅

**Comment by ScreamingHawk** [comment]
No problem :P I do that same thing all the time
