### ISSUE TITLE
Why android.permission.INTERNET ?

### ISSUE THREAD

**Issue by ttsiodras** [ScreamingHawk/phone-saver#67]
Why android.permission.INTERNET ?

Given that in your readme, you state...

    "un-features:
     No internet connection"

**Comment by ScreamingHawk** [comment]
Sorry. I need to remove that from f-droid. 

It needs `permission.INTERNET` to saved images supplied via a URL. 
Otherwise it can only save the URL text and not the content.

**Comment by ScreamingHawk** [comment]
Done here and Play Store.
