### ISSUE TITLE
Add travis ci

### ISSUE THREAD

**Issue by ScreamingHawk** [ScreamingHawk/phone-saver#70]
https://docs.travis-ci.com/user/getting-started/

**Comment by santoshhiremani** [comment]
Hey @ScreamingHawk can i take this?

**Comment by ScreamingHawk** [comment]
Sure thing! 

Travis.ci should already have permissions to access the repo. I just need the `.travis.yml` file added to get this one done.

**Comment by santoshhiremani** [comment]
OK than I will raise PR with the file

**Comment by santoshhiremani** [comment]
No, have to select our repo manually in travis. I don't have permission to add it there,  I will be committing the ` .travis.yml`, you just follow steps and give permission to access repo to travis. That should do the things.

**Comment by santoshhiremani** [comment]
Add travis is in place now...!!

**Comment by ScreamingHawk** [comment]
Woohoo! Thanks so much for this. This is going to make releases a lot quicker for me. And I'll be a lot more comfortable accepting pull requests! Thanks again.
