### ISSUE TITLE
Add FAQs and Privacy Policy

### ISSUE THREAD

**Issue by HarryHeights** [ScreamingHawk/phone-saver#73]
Hello, I'm Harry. 
I'll love to create some documents that would enhance your project even more. Privacy Policy document and FAQs. 
The policy document would state all information you collect and use while people use your software and even if you don't it'll be cool also to let them know.

The FAQs would acts as a self-service manual. It'll be a compilation of basic and advanced questions for new and already existing users of your software.

I'll love to get a reply from you.

**Comment by ScreamingHawk** [comment]
Hey Harry, 

Please do! I current don't collect any user information (beyond what is automatically collected by Google Play). FAQs are very welcome. I have a problem with usability at the moment and really I think that documentation is a patch and not a solution. But it's still a nice interim solution. 

How are you planning to contribute these? 

I'll update this ticket title to be more appropriate. 

Cheers,
Michael

**Comment by HarryHeights** [comment]
I'm more of a writer than a developer. So I only planned to just create these documents here on the project's repository. But it'll be cool if you can integrate these documents in app. They could be placed in an About section. So there's a link for users to read the FAQs and also the privacy policy. 
You can notify users of these changes with a changelog.

**Comment by ScreamingHawk** [comment]
OK, sounds good. Happy for any kind of contribution. Thanks for expressing an interest! 

My preference would be a markdown file at `docs/FAQ.md` etc, but if you have something different in mind feel free to do that.

**Comment by HarryHeights** [comment]
Alright thanks.

**Comment by HarryHeights** [comment]
Do you collect crash report information?

**Comment by ScreamingHawk** [comment]
Thanks for these Harry! Definitely going to use these as a base for my other projects. Really appreciate your work here
