### ISSUE TITLE
Support for. ogg audio?

### ISSUE THREAD

**Issue by NitroNils** [ScreamingHawk/phone-saver#77]
Tried to download a file, but was told 'unsupported'.

**Comment by ScreamingHawk** [comment]
Weird. Should be working. 

The next time you see the unsupported message, could you click the option to generate a bug request from that page? It will automatically create a ticket here with a bunch of helpful debug information for me. Like version, link, and share configuration.

**Comment by ScreamingHawk** [comment]
This ticket is now 4 months old. I'm closing it. Can be reopened if a generated bug request is posted
