### ISSUE TITLE
URL links don't follow redirects

### ISSUE THREAD

**Issue by Knightrius** [ScreamingHawk/phone-saver#78]
Support request. Generated by Phone Saver.

Intent type: text/plain
Intent action: android.intent.action.SEND
Text: http://vsco.co/loganberryy/media/5bcb9dfc793af11402fe4274?share=MTU0MDA3MDkxMA==
Application Version: 4.0.3

More information: TYPE_ADDITIONAL_INFORMATION_HERE

Thank you

**Comment by ScreamingHawk** [comment]
Error due to 302 causing a redirect from `http` to `https`. Shouldn't be too difficult, as I've just implemented for Imgur handling

**Comment by ScreamingHawk** [comment]
Actually, it's more complicated than that. 

When sharing the page, you are going to end up saving the HTML web page. If you click and hold on the image and select `Share Image` then save that, you'll end up saving the correct thing. 

I'm going to handle the redirect issue as part of this ticket, but I think the above is the real solution to your problem @Knightrius . 

Sorry it took so long to investigate this one.

**Comment by ScreamingHawk** [comment]
Redirecting link for testing: `https://im.vsco.co/aws-us-west-2/b96fdf/23497656/5bcb9dfc793af11402fe4274/vsco5bcb9dfdb5ecf.jpg?w=403&dpr=1`
