### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by DuMuT6p** [ScreamingHawk/phone-saver#79]
Hello,
Please consider having a changelog. This would help people if they want to help in testing, code or adapt specific functionality.

**Comment by ScreamingHawk** [comment]
Hi @DuMuT6p . There is a change log already. You can access it from the top right menu, and it automatically pops up when a new version is installed.

**Comment by DuMuT6p** [comment]
@ScreamingHawk Sorry for confusion, I actually meant changelog file on github. Or on releases. Also this way it can be linked on F-droid.  Linking the changelog_master.xml probably is too raw. 

But it is great that there is one in app. Not so much people do it. Thank you.

**Comment by ScreamingHawk** [comment]
Sounds like a good idea. Can you link me an example? I haven't used anything like that before

**Comment by DuMuT6p** [comment]
You can see on this repo https://github.com/SimpleMobileTools/Simple-Music-Player/blob/master/CHANGELOG.md. Each entry is also on "Releases" tab, not sure if automatic.
Also a fun site is https://keepachangelog.com/en/1.0.0/. 
Altrough just copying from you .xml can be enough.
