### ISSUE TITLE
FolderListActivity doesn't forget. Delete folder

### ISSUE THREAD

**Issue by realrufans** [ScreamingHawk/phone-saver#84]
### Expected behavior
I expected ```FolderListActivity``` to permanently forget a folder if the folder is removed.

### Actual behavior

```FolderListActivity``` pretends to forget the deleted folder. The deleted folder comes back if the user opens another activity and then comes back to  **FolderListActivity**.

### Effect 

Due to the error explained above,  the deleted folder covers the ```folder_list_empty_title``` string on the screen.

### Steps to reproduce the behavior

- launch phone saver 
- click on the **+** button, then,  add a folder
- Delete the folder 
- open settings page, then go back to FolderListActivity.
- see how the deleted folder covers the Welcome message.

### screenshot

![Screenshot_20190426-120404.png](https://cdn.steemitimages.com/DQmXQaGnG7msW2HJwyDaD1Gjd7JNdcS3KBHSM8eb99AwZse/Screenshot_20190426-120404.png)

### version
Phone saver v4.1.1
Android 8.

**Comment by realrufans** [comment]
# Possible fix?

Maybe a Walk around would be to reduce the height of the layout holding the folder list. ?

**Comment by ScreamingHawk** [comment]
Nice find! If you could create a pull request with the fix that would be amazing. If not I'll take a look at this in (hopefully) the next couple of days.

**Comment by ScreamingHawk** [comment]
Fixed it :D Will be available in the next release. Thanks again for finding this one @realrufans

**Comment by realrufans** [comment]
Tested... Working
