### ISSUE TITLE
Contributor's guidelines.

### ISSUE THREAD

**Issue by HarryHeights** [ScreamingHawk/phone-saver#86]
Hello! It's been a long time. Glad to see the project still active. I've since been expecting an update, and I'm glad to see that there's one now.
Well, I just wanted to ask if you'll be needing a contributors guide document. This will help prospective contributors and collaborators make proper contributions to the project.

**Comment by ScreamingHawk** [comment]
Hey, that'll be great!

I have this contributing doc for another project. I'd be happy to accept a PR that is just this with the repo names and links changed

https://github.com/ScreamingHawk/android-slideshow/blob/master/CONTRIBUTING.md

**Comment by ScreamingHawk** [comment]
I had a couple minutes to kill so I did this myself. Thanks for spotting the gap there @HarryHeights !!

**Comment by HarryHeights** [comment]
No qualms @ScreamingHawk . It was night here when you replied. I was sleeping.
