### ISSUE TITLE
Filename is truncated after whitespace

### ISSUE THREAD

**Issue by cges30901** [ScreamingHawk/phone-saver#90]
When I try saving a file with Phone Saver, if the filename contains whitespace, the converted filename is characters before the first whitespace. For example, if converting filename is `RPD lab BOOK2.pdf`, converted filename becomes `RPD` (without extension).

I am using ASUS Zenfone 3, Android 8.0, Phone Saver 5.2.0.

**Comment by ScreamingHawk** [comment]
Thanks for the ticket. That should be an easy one to fix

**Comment by cges30901** [comment]
This issue results from [this line](https://github.com/ScreamingHawk/phone-saver/blob/85fe850f7bca5f092ab6d805dc59fb5a05772fc7/app/src/main/java/link/standen/michael/phonesaver/activity/SaverActivity.kt#L414). If I comment it, this issue no longer happens ("Use lenient filename validation" needs to be enabled to preserve space and Chinese characters).

**Comment by ScreamingHawk** [comment]
Sorry 6 months late to this :grimacing:

**Comment by kirisakow** [comment]
Issue still present (phone-saver version 5.2.1, Android 10)

Related issue: #98

**Comment by kirisakow** [comment]
@ScreamingHawk can you please take another look at this issue? Any filename with a space in it gets truncated
