### ISSUE TITLE
Feature request: Backport to Android 5.0 or 6.0

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ScreamingHawk/phone-saver#94]
Is it possible to backport to Android version 5.0 or 6.0?

**Comment by ScreamingHawk** [comment]
Hi there. Yes it should be possible to back port. The app doesn't use a lot of advanced features. 

This isn't something I'm interested in doing for this repo. You're always welcome to fork the repo and modify for your needs, as long as the credits are retained.
